In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [75]:

sample_teks = "timnas indonesia main mantap keren banget tahan bagus serang bagus"

# Memisahkan teks menjadi kata-kata
kata_kata = sample_teks.split()

# Inisialisasi Tokenizer
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')

# Fit teks pada tokenizer
tokenizer.fit_on_texts(kata_kata)
word_index = tokenizer.word_index

print(word_index)

{'<OOV>': 1, 'bagus': 2, 'timnas': 3, 'indonesia': 4, 'main': 5, 'mantap': 6, 'keren': 7, 'banget': 8, 'tahan': 9, 'serang': 10}


In [65]:
text_sequences = tokenizer.texts_to_sequences([sample_teks])[0]
print(sample_teks)
print(text_sequences)

timnas indonesia main mantap keren banget tahan bagus serang bagus
[3, 4, 5, 6, 7, 8, 9, 2, 10, 2]


In [66]:
# Ubah list menjadi array numpy
text_sequences_array = np.array(text_sequences)
text_sequences_array.shape

(10,)

In [67]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(len(word_index) + 1, 8, input_shape=(10,), embeddings_initializer='uniform'),
])

In [68]:
# # Menambahkan dimensi tambahan ke array
# text_sequences_array_expanded = np.expand_dims(text_sequences_array, axis=0)
# text_sequences_array_expanded.shape

(1, 10)

In [69]:

# output_array = model.predict(text_sequences_array_expanded)
# print(output_array)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
[[[-0.04550374 -0.00837178 -0.01312106 -0.0063603  -0.01672603
    0.0203802   0.02742959  0.02175787]
  [-0.03447998 -0.01891717 -0.0289578   0.00302847 -0.03514106
    0.04604175  0.01941648 -0.04966583]
  [ 0.00555872  0.04359151  0.00444311  0.02589743  0.04958758
    0.00798961 -0.039342    0.0145882 ]
  [-0.02273577 -0.03395368 -0.01961151  0.03118222 -0.02350597
   -0.01414061 -0.00999259  0.02961962]
  [ 0.02457335 -0.04313856 -0.01648206  0.03935889  0.02587168
    0.03600855 -0.02544801  0.03927585]
  [-0.02560535 -0.01044355  0.04961004 -0.04908165  0.04102651
    0.02758962  0.03322483 -0.01463032]
  [ 0.04609929  0.04453552  0.00779549 -0.02719733 -0.01365424
   -0.04052832  0.04487603 -0.03613282]
  [ 0.03928185 -0.02329862 -0.04917803  0.04597708 -0.00145281
    0.01015916 -0.0147874  -0.0033261 ]
  [-0.03182508  0.03929876 -0.0297678  -0.0059512  -0.02487149
   -0.01315031 -0.0395348  -0.03583873]
  [ 0.03928185 -0.02329862 -0.04917

In [6]:
from gensim.models import Word2Vec

from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

sample_teks = "timnas indonesia mainnya mantap keren banget tahan bagus serang bagus"

# Memisahkan teks menjadi kata-kata
kata_kata = [sample_teks.split()]

# Inisialisasi Tokenizer
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')

# Fit teks pada tokenizer
tokenizer.fit_on_texts(kata_kata)
word_index = tokenizer.word_index

print(word_index)

# Mengubah teks menjadi token
text_sequences = tokenizer.texts_to_sequences(kata_kata)

# Model Word2Vec
w2v_model = Word2Vec(sentences=[sample_teks.split()], vector_size=8, window=5, min_count=1, workers=4)

# Create a weight matrix for the embedding layer
vocab_size = len(word_index) + 1  # tambahkan 1 karena indeks dimulai dari 1
embedding_matrix = np.zeros((vocab_size, 8))
for word, i in tokenizer.word_index.items():
    if word in w2v_model.wv:
        embedding_matrix[i] = w2v_model.wv[word]

# Mencari kata berdasarkan vektor tertentu
def find_word_by_vector(embedding_matrix, vector):
    for word, index in tokenizer.word_index.items():
        if np.array_equal(embedding_matrix[index], vector):
            return word, embedding_matrix[index]
    return None


# word = find_word_by_vector(embedding_matrix, embedding_matrix[8])
# print(word)


{'<OOV>': 1, 'bagus': 2, 'timnas': 3, 'indonesia': 4, 'mainnya': 5, 'mantap': 6, 'keren': 7, 'banget': 8, 'tahan': 9, 'serang': 10}


In [7]:
# Contoh: Mencari kata untuk vektor embedding_matrix[3]
for i in range(1, 11):
    word = find_word_by_vector(embedding_matrix, embedding_matrix[i])
    print(word)


('<OOV>', array([0., 0., 0., 0., 0., 0., 0., 0.]))
('bagus', array([-0.00670284,  0.00295539,  0.06379187,  0.11261591, -0.11628687,
       -0.08896011,  0.08073591,  0.11216235]))
('timnas', array([-0.0188501 ,  0.03087243, -0.01110034,  0.06917077, -0.03428721,
        0.02825081,  0.06819743,  0.10432442]))
('indonesia', array([ 0.05646876, -0.084837  , -0.04435611,  0.11748135, -0.01972066,
        0.00401714, -0.05175787, -0.0960336 ]))
('mainnya', array([ 0.06227572,  0.11541429, -0.10197397,  0.05619748, -0.05171345,
        0.0103067 ,  0.10623275, -0.05577721]))
('mantap', array([-0.12004438,  0.06259117, -0.10949482, -0.05489781, -0.00043875,
       -0.00370227, -0.0957655 ,  0.12018429]))
('keren', array([ 0.11922649, -0.09148958, -0.02917211, -0.02422176,  0.10096796,
       -0.0741362 ,  0.00056453, -0.05942167]))
('banget', array([ 0.07938613, -0.04256707, -0.01183002,  0.07210717, -0.09402047,
       -0.04920129, -0.09389478, -0.01162553]))
('tahan', array([ 0.03595725, 

In [86]:
pd.set_option('display.max_colwidth', None)

In [88]:
import numpy as np
import pandas as pd

# Bulatkan nilai-nilai dalam matriks embedding
rounded_embedding_matrix = np.round(embedding_matrix, decimals=2)

# Contoh: Mencari kata untuk vektor rounded_embedding_matrix[1]
word_list = []
vector_list = []
for i in range(1, 11):
    word, vector = find_word_by_vector(rounded_embedding_matrix, rounded_embedding_matrix[i])
    word_list.append(word)
    vector_list.append(vector)

# Membuat DataFrame
df = pd.DataFrame({
    'Word': word_list,
    'Vector': vector_list
})


df

Word                                                  Vector
0      <OOV>                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
1      bagus      [-0.01, 0.0, 0.06, 0.11, -0.12, -0.09, 0.08, 0.11]
2     timnas      [-0.02, 0.03, -0.01, 0.07, -0.03, 0.03, 0.07, 0.1]
3  indonesia     [0.06, -0.08, -0.04, 0.12, -0.02, 0.0, -0.05, -0.1]
4       main      [0.06, 0.12, -0.1, 0.06, -0.05, 0.01, 0.11, -0.06]
5     mantap     [-0.12, 0.06, -0.11, -0.05, -0.0, -0.0, -0.1, 0.12]
6      keren     [0.12, -0.09, -0.03, -0.02, 0.1, -0.07, 0.0, -0.06]
7     banget  [0.08, -0.04, -0.01, 0.07, -0.09, -0.05, -0.09, -0.01]
8      tahan       [0.04, 0.01, -0.1, -0.12, 0.09, 0.06, 0.08, 0.01]
9     serang  [-0.06, -0.05, 0.09, -0.02, -0.06, 0.08, -0.06, -0.02]

In [5]:
import tensorflow as tf
import numpy as np

# Inisialisasi Glorot uniform untuk kernel
initializer = tf.keras.initializers.GlorotUniform()

# Membuat kernel dengan ukuran 5x8
kernel_size = (5, 8)
kernel = initializer(shape=kernel_size)

# Memperoleh nilai kernel yang sudah dibulatkan
rounded_kernel = np.round(kernel, decimals=2)

print("Kernel hasil inisialisasi Glorot uniform (setelah dibulatkan):")
print(rounded_kernel)


Kernel hasil inisialisasi Glorot uniform (setelah dibulatkan):
[[ 0.23  0.53  0.45 -0.05  0.67  0.19 -0.17 -0.13]
 [ 0.19 -0.58 -0.03 -0.39 -0.18  0.03  0.21  0.68]
 [ 0.63 -0.45 -0.24  0.07 -0.52 -0.29 -0.23  0.36]
 [-0.26  0.58 -0.25  0.38 -0.41  0.07 -0.64  0.17]
 [-0.26  0.65  0.65  0.27 -0.19  0.16 -0.53  0.37]]


In [1]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.sentiment.util import mark_negation

# Contoh teks
teks = "Saya tidak suka makanan ini. Rasanya tidak enak."

# Tokenisasi teks
kata_kata = word_tokenize(teks)

# Tandai negasi dalam teks
kata_kata_dengan_negasi = mark_negation(kata_kata)

# Gabungkan kembali kata-kata menjadi teks
teks_dengan_negasi = ' '.join(kata_kata_dengan_negasi)

print("Teks dengan negasi:", teks_dengan_negasi)


Teks dengan negasi: Saya tidak suka makanan ini . Rasanya tidak enak .
