In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [75]:

sample_teks = "benerrr moist cosrx gd tanding alias awettt bagus pol"

# Memisahkan teks menjadi kata-kata
kata_kata = sample_teks.split()

# Inisialisasi Tokenizer
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')

# Fit teks pada tokenizer
tokenizer.fit_on_texts(kata_kata)
word_index = tokenizer.word_index

print(word_index)

{'<OOV>': 1, 'bagus': 2, 'timnas': 3, 'indonesia': 4, 'main': 5, 'mantap': 6, 'keren': 7, 'banget': 8, 'tahan': 9, 'serang': 10}


In [65]:
text_sequences = tokenizer.texts_to_sequences([sample_teks])[0]
print(sample_teks)
print(text_sequences)

timnas indonesia main mantap keren banget tahan bagus serang bagus
[3, 4, 5, 6, 7, 8, 9, 2, 10, 2]


In [66]:
# Ubah list menjadi array numpy
text_sequences_array = np.array(text_sequences)
text_sequences_array.shape

(10,)

In [67]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(len(word_index) + 1, 8, input_shape=(10,), embeddings_initializer='uniform'),
])

In [68]:
# # Menambahkan dimensi tambahan ke array
# text_sequences_array_expanded = np.expand_dims(text_sequences_array, axis=0)
# text_sequences_array_expanded.shape

(1, 10)

In [69]:

# output_array = model.predict(text_sequences_array_expanded)
# print(output_array)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
[[[-0.04550374 -0.00837178 -0.01312106 -0.0063603  -0.01672603
    0.0203802   0.02742959  0.02175787]
  [-0.03447998 -0.01891717 -0.0289578   0.00302847 -0.03514106
    0.04604175  0.01941648 -0.04966583]
  [ 0.00555872  0.04359151  0.00444311  0.02589743  0.04958758
    0.00798961 -0.039342    0.0145882 ]
  [-0.02273577 -0.03395368 -0.01961151  0.03118222 -0.02350597
   -0.01414061 -0.00999259  0.02961962]
  [ 0.02457335 -0.04313856 -0.01648206  0.03935889  0.02587168
    0.03600855 -0.02544801  0.03927585]
  [-0.02560535 -0.01044355  0.04961004 -0.04908165  0.04102651
    0.02758962  0.03322483 -0.01463032]
  [ 0.04609929  0.04453552  0.00779549 -0.02719733 -0.01365424
   -0.04052832  0.04487603 -0.03613282]
  [ 0.03928185 -0.02329862 -0.04917803  0.04597708 -0.00145281
    0.01015916 -0.0147874  -0.0033261 ]
  [-0.03182508  0.03929876 -0.0297678  -0.0059512  -0.02487149
   -0.01315031 -0.0395348  -0.03583873]
  [ 0.03928185 -0.02329862 -0.04917

In [7]:
from gensim.models import Word2Vec

from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

sample_teks = "benerrr moist cosrx gd tanding alias awettt bagus pol"

# Memisahkan teks menjadi kata-kata
kata_kata = [sample_teks.split()]

# Inisialisasi Tokenizer
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')

# Fit teks pada tokenizer
tokenizer.fit_on_texts(kata_kata)
word_index = tokenizer.word_index

print(word_index)

# Mengubah teks menjadi token
text_sequences = tokenizer.texts_to_sequences(kata_kata)

# Model Word2Vec
w2v_model = Word2Vec(sentences=[sample_teks.split()], vector_size=100, window=5, min_count=1, workers=4)

# Create a weight matrix for the embedding layer
vocab_size = len(word_index) + 1  # tambahkan 1 karena indeks dimulai dari 1
embedding_matrix = np.zeros((vocab_size, 100))
for word, i in tokenizer.word_index.items():
    if word in w2v_model.wv:
        embedding_matrix[i] = w2v_model.wv[word]

# Mencari kata berdasarkan vektor tertentu
def find_word_by_vector(embedding_matrix, vector):
    for word, index in tokenizer.word_index.items():
        if np.array_equal(embedding_matrix[index], vector):
            return word, embedding_matrix[index]
    return None


# word = find_word_by_vector(embedding_matrix, embedding_matrix[8])
# print(word)


{'<OOV>': 1, 'benerrr': 2, 'moist': 3, 'cosrx': 4, 'gd': 5, 'tanding': 6, 'alias': 7, 'awettt': 8, 'bagus': 9, 'pol': 10}


In [8]:
# Contoh: Mencari kata untuk vektor embedding_matrix[3]
for i in range(1, 11):
    word = find_word_by_vector(embedding_matrix, embedding_matrix[i])
    print(word)


('<OOV>', array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))
('benerrr', array([-9.57854651e-03,  8.94311536e-03,  4.16506873e-03,  9.23473481e-03,
        6.64350251e-03,  2.92473682e-03,  9.80401970e-03, -4.42464091e-03,
       -6.80331094e-03,  4.22738073e-03,  3.72899999e-03, -5.66461077e-03,
        9.70476028e-03, -3.55830672e-03,  9.54940636e-03,  8.34726088e-04,
       -6.33845665e-03, -1.97711703e-03, -7.37705454e-03, -2.97952304e-03,
        1.04169722e-03,  9.48268734e-03,  9.35584772e-03, -6.59587746e-03,
        3.47515102e-03,  2.27557053e-03, -2.48935213e-03, -9.22917202e-03,
        1

In [5]:
pd.set_option('display.max_colwidth', None)

In [13]:
import numpy as np
import pandas as pd

# Bulatkan nilai-nilai dalam matriks embedding
rounded_embedding_matrix = np.round(embedding_matrix, decimals=4)

# Contoh: Mencari kata untuk vektor rounded_embedding_matrix[1]
word_list = []
vector_list = []
for i in range(1, 11):
    word, vector = find_word_by_vector(rounded_embedding_matrix, rounded_embedding_matrix[i])
    word_list.append(word)
    vector_list.append(vector)

# Membuat DataFrame
df = pd.DataFrame({
    'Word': word_list,
    'Vector': vector_list
})


df

Word  \
0    <OOV>   
1  benerrr   
2    moist   
3    cosrx   
4       gd   
5  tanding   
6    alias   
7   awettt   
8    bagus   
9      pol   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Vector  
0                                                                                                                                                                                                                                                                                                                                                               [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
1         [-0.0096, 0.0089, 0.0042, 0.0092, 0.0066, 0.0029, 0.0098, -0.0044, -0.0068, 0.0042, 0.0037, -0.0057, 0.0097, -0.0036, 0.0095, 0.0008, -0.0063, -0.002, -0.0074, -0.003, 0.001, 0.0095, 0.0094, -0.0066, 0.0035, 0.0023, -0.0025, -0.0092, 0.001, -0.0082, 0.0063, -0.0058, 0.0055, 0.0098, -0.0002, 0.0045, -0.0018, 0.0074, 0.0039, -0.009, -0.0024, 0.0036, -0.0001, -0.0012, -0.0011, -0.0017, 0.0006, 0.0042, -0.0043, -0.0038, -0.0001, 0.0003, -0.0002, -0.0048, 0.0043, -0.0022, 0.0021, 0.0007, 0.006, -0.0068, -0.0068, -0.0045, 0.0094, -0.0016, -0.0094, -0.0005, -0.0044, 0.006, -0.0096, 0.0029, -0.0093, 0.0012, 0.006, 0.0074, -0.0076, -0.0061, -0.0068, -0.0079, -0.0095, -0.0021, -0.0008, -0.0073, 0.0068, 0.0011, 0.0058, 0.0015, 0.0008, -0.0074, -0.0022, 0.0043, -0.0051, 0.0011, 0.0029, -0.0015, 0.0099, 0.0083, 0.0024, 0.0071, 0.0059, -0.0056]  
2           [0.0082, -0.0044, 0.009, 0.0083, -0.0044, 0.0003, 0.0043, -0.0039, -0.0056, -0.0065, -0.0007, -0.0003, 0.0045, -0.0025, -0.0002, 0.0025, 0.0049, -0.0, -0.0063, -0.0093, 0.0, 0.0067, 0.0015, -0.009, -0.0079, 0.0066, -0.0038, 0.0063, -0.0067, 0.0085, -0.0065, 0.0033, -0.0011, -0.0068, -0.0033, -0.0012, -0.0055, -0.0012, -0.0076, 0.0026, 0.0091, -0.0024, -0.001, 0.0035, 0.0087, -0.0059, -0.0069, -0.0029, 0.0091, 0.0009, -0.0087, -0.0014, 0.0095, -0.0075, -0.0054, 0.0093, -0.009, 0.0038, 0.0007, 0.0067, 0.0083, -0.0029, -0.004, 0.0089, 0.0021, 0.0062, -0.0094, 0.0096, -0.0013, -0.0061, 0.003, -0.0005, 0.0047, -0.0023, -0.0041, 0.0023, 0.0084, -0.005, 0.0027, -0.008, -0.0068, -0.0005, -0.0088, 0.0028, 0.0016, -0.0023, 0.005, 0.0097, 0.0085, -0.0019, 0.0021, -0.004, -0.0082, 0.0063, -0.0019, -0.0007, -0.0018, -0.0045, 0.0041, -0.0043]  
3  [0.0081, -0.0045, -0.0011, 0.001, -0.0002, 0.0011, 0.0061, -0.0, -0.0032, -0.0015, 0.0059, 0.0015, -0.0007, 0.0093, -0.0049, -0.0008, 0.0092, 0.0067, 0.0015, -0.0089, 0.0011, -0.0023, 0.0094, 0.0012, 0.0015, 0.0024, -0.0018, -0.005, 0.0002, -0.002, 0.0066, 0.0089, -0.0007, 0.003, -0.0061, 0.0017, -0.0069, -0.0087, -0.0059, -0.009, 0.0073, -0.0058, 0.0083, -0.0072, 0.0034, 0.0097, -0.0078, -0.0099, -0.0043, -0.0027, -0.0003, 

In [28]:
import tensorflow as tf
import numpy as np

# Inisialisasi Glorot uniform untuk kernel
initializer = tf.keras.initializers.GlorotUniform()

# Membuat kernel dengan ukuran 5x8
kernel_size = (5, 8)
kernel = initializer(shape=kernel_size)

# Memperoleh nilai kernel yang sudah dibulatkan
rounded_kernel = np.round(kernel, decimals=2)

print("Kernel hasil inisialisasi Glorot uniform (setelah dibulatkan):")
print(rounded_kernel)


Kernel hasil inisialisasi Glorot uniform (setelah dibulatkan):
[[-0.1   0.37  0.04  0.52  0.57 -0.1   0.28  0.29]
 [-0.33 -0.07  0.23 -0.    0.61 -0.66 -0.24  0.67]
 [-0.4  -0.25  0.38  0.16  0.59  0.1  -0.16 -0.31]
 [-0.08  0.04  0.53  0.58  0.08 -0.4  -0.02  0.48]
 [ 0.59  0.63 -0.53 -0.45  0.63  0.31 -0.2  -0.44]]


In [29]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Fungsi untuk menghasilkan kernel yang berbeda dengan menggunakan seed yang berbeda
def create_unique_kernel(seed, kernel_size):
    initializer = tf.keras.initializers.GlorotUniform(seed=seed)
    kernel = initializer(shape=kernel_size).numpy()
    return np.round(kernel, decimals=2).flatten()

# Ukuran kernel
kernel_size = (5, 8)

# Membuat 127 kernel dengan inisialisasi berbeda menggunakan seed yang berbeda
kernels = []
for i in range(127):
    kernel = create_unique_kernel(seed=i, kernel_size=kernel_size)
    kernels.append(kernel)

# Konversi ke DataFrame dan menambahkan kolom deskripsi
df = pd.DataFrame(kernels, columns=[f'Value_{i}' for i in range(kernel_size[0] * kernel_size[1])])
df.insert(0, 'Deskripsi', [f'Kernel ke-{i+1}' for i in range(127)])

# Menyimpan ke CSV
df.to_csv('kernels.csv', index=False)

print("127 kernel telah disimpan ke kernels.csv dengan keterangan yang sesuai.")


127 kernel telah disimpan ke kernels.csv dengan keterangan yang sesuai.
