In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
# Jumlah neuron pada lapisan input
input_neurons = 1

# # Jumlah neuron pada lapisan tersembunyi
hidden_neurons = 16

# # Inisialisasi bobot secara acak dengan distribusi uniform dari -1 hingga 1
weight_matrix_hidden = np.random.uniform(low=-1, high=1, size=(input_neurons, hidden_neurons))

# # Membulatkan nilai bobot menjadi bilangan bulat
rounded_weight_matrix_hidden = np.round(weight_matrix_hidden, 2)

print("Weight matrix shape:", rounded_weight_matrix_hidden.shape)
print("Weight matrix values:\n", rounded_weight_matrix_hidden)



Weight matrix shape: (1, 16)
Weight matrix values:
 [[-0.59 -0.63 -0.13  0.41 -0.88  0.42 -0.79 -0.3   0.66 -0.26  0.96  0.87
   0.28  0.46 -0.02 -0.22]]


In [3]:
import numpy as np

# Fungsi aktivasi ReLU
def relu(x):
    return np.maximum(0, x)

# Input dari hasil konvolusi
# timnas indonesia main mantap keren banget tahan bagus serang bagus
input_vector = np.array([0.1683])


# Hitung feedforward
print(np.dot(input_vector, rounded_weight_matrix_hidden))
output_vector_hidden = relu(np.dot(input_vector, rounded_weight_matrix_hidden))

print("Output vector:")
print(output_vector_hidden)


[-0.099297 -0.106029 -0.021879  0.069003 -0.148104  0.070686 -0.132957
 -0.05049   0.111078 -0.043758  0.161568  0.146421  0.047124  0.077418
 -0.003366 -0.037026]
Output vector:
[0.       0.       0.       0.069003 0.       0.070686 0.       0.
 0.111078 0.       0.161568 0.146421 0.047124 0.077418 0.       0.      ]


In [6]:
# Jumlah neuron pada lapisan input
hidden_neurons = 16

# Jumlah neuron pada lapisan tersembunyi
output_layer_neurons = 3

# Inisialisasi bobot secara acak dengan distribusi uniform dari -1 hingga 1
weight_matrix = np.random.uniform(low=-1, high=1, size=(hidden_neurons, output_layer_neurons))

# Membulatkan nilai bobot menjadi bilangan bulat
rounded_weight_matrix_output = np.round(weight_matrix, 2)

print("Weight matrix shape:", rounded_weight_matrix_output.shape)
print("Weight matrix values:\n", rounded_weight_matrix_output)

Weight matrix shape: (16, 3)
Weight matrix values:
 [[ 0.76 -0.53  0.26]
 [-0.    0.86 -0.27]
 [-0.32 -0.11  0.21]
 [ 0.01 -0.16  0.58]
 [ 0.36 -0.78 -0.79]
 [-0.43 -0.6  -0.3 ]
 [-0.7   0.66  0.68]
 [ 0.12  0.67 -0.08]
 [ 0.85  0.99  0.55]
 [-0.63  0.86  0.07]
 [-0.21  0.17 -0.09]
 [ 0.95  0.93 -0.27]
 [ 0.72 -0.3   1.  ]
 [ 0.    0.11  0.09]
 [-0.74 -0.09  0.04]
 [ 0.23  0.13  0.36]]


In [7]:
import numpy as np


# def sigmoid(x):
#     return 1 / (1 + np.exp(-x))

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

# Mengupdate bobot secara acak hingga output vektor softmax pada indeks ke-2 lebih besar dari yang lainnya
while True:
    # Mendapatkan output vector dengan bobot yang terbaru
    output_dot = np.dot(output_vector_hidden, rounded_weight_matrix_output)
    output_final = softmax(output_dot)
    
    # Jika output vektor pada indeks ke-2 lebih besar daripada yang lainnya, hentikan loop
    if output_final[2] > output_final[0] and output_final[2] > output_final[1]:
        break
    
    # Jika tidak, update bobot secara acak
    rounded_weight_matrix_output = np.random.uniform(low=-1.0, high=1.0, size=rounded_weight_matrix_output.shape)

print("\nOutput dot vector")
print(output_dot)
print("\nUpdated weight matrix:")
print(rounded_weight_matrix_output)
print("\nOutput vector sigmoid:")
print(output_final)



Output dot vector
[-0.24313791  0.25420849  0.37355009]

Updated weight matrix:
[[-0.98327151  0.55373063  0.85962628]
 [-0.13533225 -0.55907465  0.79711341]
 [-0.57972138 -0.89935898 -0.43267666]
 [-0.69278409  0.54588971  0.81375545]
 [ 0.49784574 -0.68688994  0.9190191 ]
 [ 0.77901555 -0.82800763 -0.8221733 ]
 [-0.32559461  0.19572018  0.11156684]
 [ 0.72498565  0.53520911  0.65001949]
 [-0.53748278  0.77784836  0.80553744]
 [ 0.73767698  0.10450657  0.14834182]
 [-0.90225649  0.51111708  0.6140748 ]
 [-0.4630794   0.93860538  0.92218875]
 [ 0.19432008 -0.03558168 -0.17381765]
 [ 0.17730345 -0.38321549  0.77482664]
 [-0.66312186 -0.94972653 -0.98742188]
 [ 0.85900352  0.82972158  0.24077662]]

Output vector sigmoid:
[0.22236387 0.36564448 0.41199165]


: 